branches:
  - main

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@semantic-release/exec'
    - prepareCmd: "./semantic-release-build.sh ${nextRelease.version}"
  - - '@semantic-release/github'
    - assets:
      - target/thumbv6m-none-eabi/release/bloop-nfc-scanner.uf2
  - - '@semantic-release/git'
    - assets:
      - CHANGELOG.md
      - Cargo.toml
      - Cargo.lock
      message: "chore(release): set `Cargo.toml` to ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
