name: CI

on:
  push:
    branches:
      - main

env:
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-02-07
      - run: cargo check

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-02-07
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-02-07
          components: clippy
      - run: cargo clippy -- -D warnings

  release:
    needs: [check, fmt, clippy]
    name: Semantic Release
    runs-on: ubuntu-latest
    if: github.actor != 'sbosnick-bot'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-02-07

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: semantic
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/changelog@6.0
            @semantic-release/exec@6.0
            @semantic-release/git@10.0
